services:
  db:
    image: postgres:9.5
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=whiteboard_user
      - POSTGRES_DB=whiteboard
    env_file:
      - docker.env
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/whiteboard/
    links:
      - "db:database.com"
    tty: true
    stdin_open: true
    env_file:
      - docker.env
    command: sh -c "bundle exec rake assets:precompile && bundle exec rake db:migrate && bundle exec unicorn -p 3000 -c ./config/unicorn.rb"
    depends_on:
      - db
  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    links:
      - "app:whiteboard.com"
volumes:
  db-store:
